services:
  redis:
    image: redis:alpine
    ports:
      - "6381:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
      image: postgres:14-alpine
      restart: always
      env_file:
        - ../src/.env
      volumes:
        - postgres_data:/var/lib/postgresql/data
      ports:
        - "5435:5432"

  web:
    build:
      context: ../
      dockerfile: devops/Dockerfile
    image: worknest-app
    working_dir: /app/src
    volumes:
      - static_volume:/var/www/static
      - media_volume:/app/src/static/media
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_started
    env_file:
      - ../src/.env

  celery_worker:
    image: worknest-app
    entrypoint: [ "/entrypoint.sh" ]
    command: ["celery", "worker","-E"]
    working_dir: /app/src
    depends_on:
      - redis
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - static_volume:/var/www/static
    env_file:
      - ../src/.env


  celery_beat:
    image: worknest-app
    entrypoint: ["/entrypoint.sh"]
    command: [ "celery", "beat", "--schedule=/app/src/celerybeat-schedule" ]
    working_dir: /app/src
    depends_on:
      - redis
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - static_volume:/var/www/static
    env_file:
      - ../src/.env


  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    depends_on:
      - redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/var/www/static
      - media_volume:/app/src/static/media
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
