# Generated by Django 5.2.4 on 2025-07-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('full_name', models.CharField(max_length=128, verbose_name='Full name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone number')),
                ('subject', models.CharField(choices=[('job', 'Job / Collaboration'), ('tech', 'Technical Question'), ('other', 'Other')], default='other', max_length=32, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is read?')),
                ('is_replied', models.BooleanField(default=False, verbose_name='Is replied?')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
