# Generated by Django 5.2.4 on 2025-07-29 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contactus', 'verbose_name_plural': 'Contactus'},
        ),
    ]
