# Generated by Django 5.2.4 on 2025-07-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creation_at',
            field=models.CharField(blank=True, null=True, verbose_name='Creation At'),
        ),
    ]
