# Generated by Django 5.2.4 on 2025-07-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('company_name', models.CharField(max_length=128, verbose_name='Company Name')),
                ('position', models.CharField(max_length=128, verbose_name='Job Title')),
                ('start_date', models.CharField(max_length=128, verbose_name='Start Date')),
                ('end_date', models.CharField(default='now', max_length=128, verbose_name='End Date')),
                ('location', models.CharField(blank=True, max_length=128, verbose_name='Location')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Job Experience',
                'verbose_name_plural': 'Job Experiences',
            },
        ),
    ]
